export type CimaE3Question = {
  id: number;
  topic: string;
  prompt: string;
  options: string[];
  answer: number;
  explanation: string;
};

const questions: CimaE3Question[] = [
  {
    id: 1,
    topic: "Strategic Management - Environmental analysis",
    prompt: "Which tool is most useful for identifying external opportunities and threats in a business environment?",
    options: ["SWOT analysis", "Balanced scorecard", "Budget variance analysis", "Inventory turnover ratio"],
    answer: 0,
    explanation: "A SWOT analysis helps you assess internal strengths and weaknesses alongside external opportunities and threats.",
  },
  {
    id: 2,
    topic: "Strategic Management - Competitive advantage",
    prompt: "A firm gains a sustainable competitive advantage when it is able to:",
    options: ["Match rivals' prices", "Copy competitors' products quickly", "Create value that customers perceive as superior", "Reduce staff numbers every quarter"],
    answer: 2,
    explanation: "Sustainable advantage comes from delivering unique value that is difficult for competitors to replicate.",
  },
  {
    id: 3,
    topic: "Strategic Management - Strategic choices",
    prompt: "Which strategy focuses on entering new markets with existing products?",
    options: ["Market penetration", "Market development", "Diversification", "Product development"],
    answer: 1,
    explanation: "Market development means selling existing products in new markets or customer segments.",
  },
  {
    id: 4,
    topic: "Strategic Management - Stakeholder management",
    prompt: "Why is stakeholder analysis important in strategic planning?",
    options: ["It removes the need for governance", "It identifies who can influence or be affected by strategy", "It guarantees successful implementation", "It replaces financial forecasting"],
    answer: 1,
    explanation: "Stakeholder analysis helps leaders understand interests, power, and potential impact on implementation.",
  },
  {
    id: 5,
    topic: "Strategic Management - Change management",
    prompt: "Which action best supports successful strategic change?",
    options: ["Ignoring employee concerns", "Communicating the vision clearly", "Delaying decisions until the market stabilizes", "Avoiding performance measurement"],
    answer: 1,
    explanation: "Clear communication and engagement are key to successful strategic change.",
  },
  {
    id: 6,
    topic: "Strategic Management - Performance measurement",
    prompt: "Which measure is most directly linked to strategy execution?",
    options: ["Daily office attendance", "Key performance indicators", "Number of meetings held", "Office decoration budget"],
    answer: 1,
    explanation: "KPIs translate strategy into measurable outcomes that can be monitored and managed.",
  },

  // ---------------------------------------------------------------------------
  // E3 syllabus area A: The strategy process
  // ---------------------------------------------------------------------------
  {
    id: 7,
    topic: "The strategy process - Levels of strategy",
    prompt: "At which level of strategy does an organisation decide which industries or markets to compete in?",
    options: ["Corporate strategy", "Business strategy", "Operational strategy", "Functional tactics"],
    answer: 0,
    explanation: "Corporate strategy concerns the overall scope of the organisation and which businesses or markets it competes in.",
  },
  {
    id: 8,
    topic: "The strategy process - Levels of strategy",
    prompt: "Business-level strategy is mainly concerned with:",
    options: ["How the whole group allocates resources", "How a particular business unit competes in its market", "Day-to-day departmental tasks", "The personal goals of directors"],
    answer: 1,
    explanation: "Business (competitive) strategy focuses on how a strategic business unit competes successfully in its chosen market.",
  },
  {
    id: 9,
    topic: "The strategy process - Rational vs emergent strategy",
    prompt: "Mintzberg argued that, in practice, the strategy an organisation realises is often:",
    options: ["Entirely deliberate and planned", "A blend of deliberate and emergent strategy", "Always identical to the intended strategy", "Set only by external consultants"],
    answer: 1,
    explanation: "Realised strategy typically combines deliberate (planned) elements with emergent strategies that arise over time.",
  },
  {
    id: 10,
    topic: "The strategy process - Rational planning model",
    prompt: "A common criticism of the rational (formal) planning approach to strategy is that it:",
    options: ["Encourages constant flexibility", "Can be too rigid and slow in turbulent environments", "Ignores objectives entirely", "Cannot be documented"],
    answer: 1,
    explanation: "The rational model can be inflexible and may respond poorly to fast-changing, uncertain conditions.",
  },
  {
    id: 11,
    topic: "The strategy process - Logical incrementalism",
    prompt: "Logical incrementalism describes strategy that develops through:",
    options: ["One large, irreversible decision", "Small, evolving steps and continuous adjustment", "Random, unconnected actions", "Copying competitors exactly"],
    answer: 1,
    explanation: "Logical incrementalism (Quinn) sees strategy emerging through deliberate, small, continual adjustments.",
  },
  {
    id: 12,
    topic: "The strategy process - Mission and vision",
    prompt: "Which statement best describes an organisation's mission?",
    options: ["A detailed annual budget", "Its fundamental purpose and reason for existing", "A list of its competitors", "A short-term sales target"],
    answer: 1,
    explanation: "A mission states the organisation's basic purpose - what it is and why it exists.",
  },
  {
    id: 13,
    topic: "The strategy process - Objectives",
    prompt: "Objectives are often described as SMART. The 'M' stands for:",
    options: ["Motivational", "Measurable", "Marketable", "Mandatory"],
    answer: 1,
    explanation: "SMART objectives are Specific, Measurable, Achievable, Relevant and Time-bound.",
  },
  {
    id: 14,
    topic: "The strategy process - Mission versus objectives",
    prompt: "Compared with a mission statement, objectives are:",
    options: ["Vaguer and timeless", "Specific and measurable targets", "Only for the marketing department", "Never communicated internally"],
    answer: 1,
    explanation: "Objectives translate the broad mission into specific, measurable targets.",
  },
  {
    id: 15,
    topic: "The strategy process - Not-for-profit context",
    prompt: "A key feature of strategy in not-for-profit organisations is that:",
    options: ["Profit maximisation is the only objective", "Multiple stakeholder objectives and value for money dominate", "Strategy is unnecessary", "There are no external influences"],
    answer: 1,
    explanation: "Not-for-profits pursue multiple stakeholder goals and emphasise value for money rather than profit.",
  },
  {
    id: 16,
    topic: "The strategy process - Strategy in SMEs",
    prompt: "Compared with large firms, strategy in small and medium-sized enterprises tends to be:",
    options: ["Highly formalised and bureaucratic", "More informal and influenced by the owner-manager", "Set by a large planning department", "Unaffected by resource constraints"],
    answer: 1,
    explanation: "SME strategy is usually informal and strongly shaped by the owner-manager's vision and resources.",
  },
  {
    id: 17,
    topic: "The strategy process - Corporate governance",
    prompt: "The primary strategic role of the board of directors is to:",
    options: ["Perform daily operational tasks", "Provide direction and oversight on behalf of stakeholders", "Prepare individual customer invoices", "Avoid setting any objectives"],
    answer: 1,
    explanation: "The board sets strategic direction and provides governance and oversight for stakeholders.",
  },
  {
    id: 18,
    topic: "The strategy process - Strategic leadership",
    prompt: "Transformational leadership supports strategy mainly by:",
    options: ["Maintaining the status quo", "Inspiring and motivating change toward a shared vision", "Focusing only on punishment", "Avoiding communication"],
    answer: 1,
    explanation: "Transformational leaders inspire followers and drive change toward a compelling vision.",
  },
  {
    id: 19,
    topic: "The strategy process - Values and culture",
    prompt: "An organisation's values are best described as:",
    options: ["Its tax obligations", "The core beliefs and principles guiding behaviour", "Its inventory levels", "Its share price"],
    answer: 1,
    explanation: "Values are the core principles and beliefs that guide how an organisation and its people behave.",
  },
  {
    id: 20,
    topic: "The strategy process - Gap analysis",
    prompt: "Gap analysis in strategic planning compares:",
    options: ["Two competitors' logos", "Forecast performance against desired objectives", "Last year's and this year's office rent", "Two suppliers' delivery times"],
    answer: 1,
    explanation: "Gap analysis identifies the difference between projected and target performance so strategies can close the gap.",
  },
  {
    id: 21,
    topic: "The strategy process - Purpose and shareholders",
    prompt: "The shareholder wealth view of organisational purpose emphasises:",
    options: ["Maximising long-term returns to owners", "Ignoring profitability", "Equal weight to every passer-by", "Eliminating all risk"],
    answer: 0,
    explanation: "The shareholder view holds that the organisation's primary purpose is to maximise owner wealth.",
  },
  {
    id: 22,
    topic: "The strategy process - Rational model sequence",
    prompt: "In the rational strategy model, which activity normally comes first?",
    options: ["Implementation", "Strategic analysis", "Control and review", "Reward allocation"],
    answer: 1,
    explanation: "The rational model runs analysis, then choice, then implementation - analysis comes first.",
  },

  // ---------------------------------------------------------------------------
  // E3 syllabus area B: Analysing the organisational ecosystem
  // ---------------------------------------------------------------------------
  {
    id: 23,
    topic: "Ecosystem analysis - PESTEL",
    prompt: "In PESTEL analysis, changes in interest rates and inflation are classified as:",
    options: ["Political factors", "Economic factors", "Social factors", "Legal factors"],
    answer: 1,
    explanation: "Interest rates and inflation are macro-economic factors.",
  },
  {
    id: 24,
    topic: "Ecosystem analysis - PESTEL",
    prompt: "An ageing population would be analysed under which PESTEL heading?",
    options: ["Technological", "Social", "Legal", "Political"],
    answer: 1,
    explanation: "Demographic trends such as an ageing population are social (socio-cultural) factors.",
  },
  {
    id: 25,
    topic: "Ecosystem analysis - PESTEL",
    prompt: "New data-protection legislation primarily affects which PESTEL factor?",
    options: ["Economic", "Legal", "Environmental", "Social"],
    answer: 1,
    explanation: "Legislation such as data-protection law is a legal factor.",
  },
  {
    id: 26,
    topic: "Ecosystem analysis - Porter's Five Forces",
    prompt: "Which of the following is NOT one of Porter's five competitive forces?",
    options: ["Threat of new entrants", "Bargaining power of suppliers", "Government subsidy levels", "Threat of substitutes"],
    answer: 2,
    explanation: "The five forces are new entrants, suppliers, buyers, substitutes and competitive rivalry; government is not one of them.",
  },
  {
    id: 27,
    topic: "Ecosystem analysis - Porter's Five Forces",
    prompt: "High barriers to entry in an industry tend to:",
    options: ["Increase the threat of new entrants", "Reduce the threat of new entrants", "Eliminate rivalry", "Increase buyer power"],
    answer: 1,
    explanation: "High entry barriers make it harder for new competitors to enter, reducing that threat.",
  },
  {
    id: 28,
    topic: "Ecosystem analysis - Porter's Five Forces",
    prompt: "Buyer (customer) bargaining power is likely to be high when:",
    options: ["There are many small buyers", "Buyers are few, large and can switch easily", "The product is unique", "Switching costs are very high"],
    answer: 1,
    explanation: "Few large buyers facing low switching costs have strong bargaining power.",
  },
  {
    id: 29,
    topic: "Ecosystem analysis - Porter's Five Forces",
    prompt: "Which factor increases the threat of substitutes?",
    options: ["Substitutes offering a better price/performance trade-off", "No alternative products existing", "Very high brand loyalty", "Strong patents on the product"],
    answer: 0,
    explanation: "Substitutes are more threatening when they offer a superior price-performance trade-off.",
  },
  {
    id: 30,
    topic: "Ecosystem analysis - Value chain",
    prompt: "In Porter's value chain, which of the following is a PRIMARY activity?",
    options: ["Procurement", "Human resource management", "Operations", "Firm infrastructure"],
    answer: 2,
    explanation: "Primary activities are inbound logistics, operations, outbound logistics, marketing and sales, and service; the others are support activities.",
  },
  {
    id: 31,
    topic: "Ecosystem analysis - Value chain",
    prompt: "Technology development and procurement are classified in the value chain as:",
    options: ["Primary activities", "Support activities", "Margins", "Substitutes"],
    answer: 1,
    explanation: "Procurement, technology development, HRM and firm infrastructure are support activities.",
  },
  {
    id: 32,
    topic: "Ecosystem analysis - Resource-based view",
    prompt: "According to the resource-based view, sustainable competitive advantage comes mainly from:",
    options: ["Cheap short-term borrowing", "Valuable, rare and hard-to-imitate resources", "Copying rivals' adverts", "Holding large cash balances"],
    answer: 1,
    explanation: "The resource-based view stresses resources and competences that are valuable, rare, inimitable and organised (VRIO).",
  },
  {
    id: 33,
    topic: "Ecosystem analysis - VRIO framework",
    prompt: "In the VRIO framework, the 'O' refers to whether the firm is:",
    options: ["Overseas", "Organised to exploit the resource", "Oversized", "Outsourced"],
    answer: 1,
    explanation: "VRIO asks if a resource is Valuable, Rare, costly to Imitate, and whether the firm is Organised to capture its value.",
  },
  {
    id: 34,
    topic: "Ecosystem analysis - Core competences",
    prompt: "Hamel and Prahalad's 'core competences' are best described as:",
    options: ["Routine tasks any firm can do", "Collective skills underpinning many products that are hard to copy", "The firm's office locations", "Short-term cost savings"],
    answer: 1,
    explanation: "Core competences are distinctive bundles of skills and technologies that give access to many markets and are hard to imitate.",
  },
  {
    id: 35,
    topic: "Ecosystem analysis - Stakeholder mapping",
    prompt: "In Mendelow's matrix, stakeholders with high power and high interest should be:",
    options: ["Kept informed only", "Managed closely as key players", "Ignored", "Given minimal effort"],
    answer: 1,
    explanation: "High-power, high-interest stakeholders are key players to be managed closely.",
  },
  {
    id: 36,
    topic: "Ecosystem analysis - Stakeholder mapping",
    prompt: "In Mendelow's matrix, a stakeholder with high power but low interest should be:",
    options: ["Kept satisfied", "Managed with minimal effort", "Treated as a key player", "Disregarded entirely"],
    answer: 0,
    explanation: "High-power, low-interest stakeholders should be kept satisfied so their interest is not aroused negatively.",
  },
  {
    id: 37,
    topic: "Ecosystem analysis - Scenario planning",
    prompt: "Scenario planning is most useful when the environment is characterised by:",
    options: ["Certainty and stability", "High uncertainty and long time horizons", "No external change", "Perfect information"],
    answer: 1,
    explanation: "Scenario planning helps organisations prepare for several plausible futures under high uncertainty.",
  },
  {
    id: 38,
    topic: "Ecosystem analysis - Competitor analysis",
    prompt: "A competitor 'response profile' tries to predict:",
    options: ["The competitor's office colour", "How the competitor is likely to react to strategic moves", "The auditor's opinion", "The weather"],
    answer: 1,
    explanation: "Competitor analysis assesses likely competitor reactions to anticipate and plan strategic moves.",
  },
  {
    id: 39,
    topic: "Ecosystem analysis - Benchmarking",
    prompt: "Comparing your processes against the best performers in any industry is known as:",
    options: ["Internal benchmarking", "Best-in-class (generic) benchmarking", "Budgeting", "Variance analysis"],
    answer: 1,
    explanation: "Best-in-class (generic) benchmarking compares against the best performers regardless of industry.",
  },
  {
    id: 40,
    topic: "Ecosystem analysis - SWOT",
    prompt: "In a SWOT analysis, a firm's strong brand reputation is best classified as:",
    options: ["An opportunity", "A strength", "A threat", "A weakness"],
    answer: 1,
    explanation: "A strong brand is an internal strength.",
  },
  {
    id: 41,
    topic: "Ecosystem analysis - Big data",
    prompt: "The 'three Vs' often used to characterise big data are volume, variety and:",
    options: ["Velocity", "Validity", "Vision", "Value chain"],
    answer: 0,
    explanation: "Big data is commonly described by volume, variety and velocity (sometimes extended with veracity and value).",
  },
  {
    id: 42,
    topic: "Ecosystem analysis - Data analytics",
    prompt: "Predictive analytics is mainly concerned with:",
    options: ["Reporting what happened last year", "Forecasting what is likely to happen", "Recording transactions", "Filing tax returns"],
    answer: 1,
    explanation: "Predictive analytics uses data and models to forecast likely future outcomes.",
  },
  {
    id: 43,
    topic: "Ecosystem analysis - Business ecosystems",
    prompt: "A 'business ecosystem' refers to:",
    options: ["A single isolated firm", "A network of interdependent organisations creating value together", "A government department", "An internal audit team"],
    answer: 1,
    explanation: "A business ecosystem is a community of interacting organisations - suppliers, partners and customers - co-creating value.",
  },
  {
    id: 44,
    topic: "Ecosystem analysis - Industry life cycle",
    prompt: "In the maturity stage of an industry life cycle, a typical feature is:",
    options: ["Rapid market growth and few competitors", "Slowing growth, intense competition and price pressure", "No customers", "Unlimited profits for all"],
    answer: 1,
    explanation: "Mature industries see slowing growth, strong rivalry and pressure on margins.",
  },

  // ---------------------------------------------------------------------------
  // E3 syllabus area C: Generating strategic options
  // ---------------------------------------------------------------------------
  {
    id: 45,
    topic: "Strategic options - Porter's generic strategies",
    prompt: "Porter's three generic strategies are cost leadership, focus and:",
    options: ["Diversification", "Differentiation", "Divestment", "Delegation"],
    answer: 1,
    explanation: "Porter's generic strategies are cost leadership, differentiation and focus.",
  },
  {
    id: 46,
    topic: "Strategic options - Cost leadership",
    prompt: "A cost leadership strategy seeks to:",
    options: ["Charge the highest prices in the market", "Be the lowest-cost producer in the industry", "Offer the most features regardless of cost", "Serve only one tiny niche"],
    answer: 1,
    explanation: "Cost leaders aim to be the lowest-cost producer, enabling competitive pricing or higher margins.",
  },
  {
    id: 47,
    topic: "Strategic options - Differentiation",
    prompt: "A differentiation strategy is most likely to succeed when:",
    options: ["Customers value and will pay for unique attributes", "All customers buy purely on lowest price", "The product is a pure commodity", "There is no brand awareness"],
    answer: 0,
    explanation: "Differentiation works when customers value distinctive features enough to pay a premium.",
  },
  {
    id: 48,
    topic: "Strategic options - Stuck in the middle",
    prompt: "Porter warned that a firm failing to commit to cost leadership or differentiation may become:",
    options: ["A market leader", "'Stuck in the middle' with below-average performance", "Automatically the most profitable", "A monopoly"],
    answer: 1,
    explanation: "Porter argued firms pursuing neither strategy clearly risk being 'stuck in the middle'.",
  },
  {
    id: 49,
    topic: "Strategic options - Focus strategy",
    prompt: "A focus (niche) strategy concentrates on:",
    options: ["The entire mass market", "A narrow segment served better than broad rivals", "Every possible customer worldwide", "Only internal staff"],
    answer: 1,
    explanation: "A focus strategy targets a specific narrow segment, serving it better than broad-line competitors.",
  },
  {
    id: 50,
    topic: "Strategic options - Bowman's strategy clock",
    prompt: "Bowman's strategy clock extends Porter by analysing strategies in terms of:",
    options: ["Price and perceived value", "Colour and shape", "Tax and audit", "Staff numbers"],
    answer: 0,
    explanation: "Bowman's clock maps competitive positions against perceived value and price.",
  },
  {
    id: 51,
    topic: "Strategic options - Ansoff matrix",
    prompt: "Selling existing products to existing markets to win greater share is:",
    options: ["Market penetration", "Product development", "Market development", "Diversification"],
    answer: 0,
    explanation: "Market penetration grows share of existing markets with existing products.",
  },
  {
    id: 52,
    topic: "Strategic options - Ansoff matrix",
    prompt: "Developing new products for existing markets is described by Ansoff as:",
    options: ["Market development", "Product development", "Market penetration", "Diversification"],
    answer: 1,
    explanation: "Product development means new products sold into existing markets.",
  },
  {
    id: 53,
    topic: "Strategic options - Ansoff matrix",
    prompt: "Which Ansoff option generally carries the highest risk?",
    options: ["Market penetration", "Market development", "Product development", "Diversification"],
    answer: 3,
    explanation: "Diversification (new products and new markets) is riskiest because both are unfamiliar.",
  },
  {
    id: 54,
    topic: "Strategic options - Methods of growth",
    prompt: "Growing by internal investment using the firm's own resources is called:",
    options: ["Organic growth", "Acquisition", "Merger", "Franchising"],
    answer: 0,
    explanation: "Organic (internal) growth uses the firm's own resources rather than buying other firms.",
  },
  {
    id: 55,
    topic: "Strategic options - Acquisitions",
    prompt: "A commonly cited advantage of growth by acquisition over organic growth is:",
    options: ["It is always cheaper", "Faster access to markets, capacity or capabilities", "It never fails", "It avoids all integration issues"],
    answer: 1,
    explanation: "Acquisitions can deliver speed - quick access to markets, assets or competences - though integration is a key risk.",
  },
  {
    id: 56,
    topic: "Strategic options - Strategic alliances",
    prompt: "A joint venture differs from a looser alliance because it usually involves:",
    options: ["Creating a separate jointly owned entity", "No sharing of resources", "One firm buying the other", "Only a short email agreement"],
    answer: 0,
    explanation: "A joint venture creates a new, separate entity jointly owned by the partners.",
  },
  {
    id: 57,
    topic: "Strategic options - International strategy",
    prompt: "Yip's globalisation drivers include market, cost, government and:",
    options: ["Weather drivers", "Competitive drivers", "Audit drivers", "Payroll drivers"],
    answer: 1,
    explanation: "Yip's drivers are market, cost, government and competitive drivers.",
  },
  {
    id: 58,
    topic: "Strategic options - Market entry modes",
    prompt: "Which foreign market entry mode generally involves the LEAST risk and commitment?",
    options: ["Wholly owned subsidiary", "Exporting", "Joint venture", "Building a local factory"],
    answer: 1,
    explanation: "Exporting typically requires the least investment and risk among entry modes.",
  },
  {
    id: 59,
    topic: "Strategic options - BCG matrix",
    prompt: "In the BCG matrix, a product with high market share in a low-growth market is a:",
    options: ["Star", "Cash cow", "Question mark", "Dog"],
    answer: 1,
    explanation: "High share with low growth is a cash cow, generating steady cash.",
  },
  {
    id: 60,
    topic: "Strategic options - BCG matrix",
    prompt: "A 'question mark' (problem child) in the BCG matrix has:",
    options: ["High share, high growth", "Low share, high growth", "High share, low growth", "Low share, low growth"],
    answer: 1,
    explanation: "Question marks have low share in high-growth markets and need investment to build share.",
  },
  {
    id: 61,
    topic: "Strategic options - Product life cycle",
    prompt: "During the growth phase of the product life cycle, sales typically:",
    options: ["Fall rapidly", "Rise rapidly as the market expands", "Stay at zero", "Are unaffected by demand"],
    answer: 1,
    explanation: "In the growth phase, sales increase quickly as adoption spreads.",
  },
  {
    id: 62,
    topic: "Strategic options - Blue ocean strategy",
    prompt: "'Blue ocean' strategy seeks competitive success by:",
    options: ["Fighting rivals in existing crowded markets", "Creating new, uncontested market space", "Cutting prices to zero", "Copying the market leader"],
    answer: 1,
    explanation: "Blue ocean strategy creates new demand in uncontested space rather than competing in crowded 'red oceans'.",
  },
  {
    id: 63,
    topic: "Strategic options - Disruptive innovation",
    prompt: "Disruptive innovation, as defined by Christensen, typically:",
    options: ["Starts simpler and cheaper, then improves to displace incumbents", "Is always more expensive at launch", "Only affects governments", "Never reaches mainstream customers"],
    answer: 0,
    explanation: "Disruptive innovations often begin simpler and cheaper, then improve and displace established offerings.",
  },
  {
    id: 64,
    topic: "Strategic options - Game theory",
    prompt: "Game theory is useful in strategy because it analyses:",
    options: ["Random luck only", "Interdependent decisions where each player anticipates others' moves", "Accounting depreciation", "Office layout"],
    answer: 1,
    explanation: "Game theory models strategic interdependence, where outcomes depend on competitors' reactions.",
  },

  // ---------------------------------------------------------------------------
  // E3 syllabus area D: Making strategic choices
  // ---------------------------------------------------------------------------
  {
    id: 65,
    topic: "Strategic choice - SAF framework",
    prompt: "Johnson, Scholes and Whittington's criteria for evaluating strategies are suitability, acceptability and:",
    options: ["Flexibility", "Feasibility", "Frequency", "Familiarity"],
    answer: 1,
    explanation: "The SAF framework tests suitability, acceptability and feasibility.",
  },
  {
    id: 66,
    topic: "Strategic choice - Suitability",
    prompt: "'Suitability' in strategy evaluation asks whether the strategy:",
    options: ["Can be financed and resourced", "Addresses the organisation's situation and strategic logic", "Is acceptable to stakeholders", "Uses the cheapest supplier"],
    answer: 1,
    explanation: "Suitability assesses whether a strategy fits the organisation's situation and strategic position.",
  },
  {
    id: 67,
    topic: "Strategic choice - Acceptability",
    prompt: "Acceptability is mainly concerned with:",
    options: ["Whether expected return, risk and stakeholder reactions are acceptable", "Whether the office is large enough", "Whether the logo is attractive", "Whether staff like the canteen"],
    answer: 0,
    explanation: "Acceptability considers expected returns, risk and stakeholder reactions to the strategy.",
  },
  {
    id: 68,
    topic: "Strategic choice - Feasibility",
    prompt: "Feasibility evaluation focuses on whether the organisation has the:",
    options: ["Right strategic logic", "Resources and competences to implement the strategy", "Best advertising slogan", "Lowest tax rate"],
    answer: 1,
    explanation: "Feasibility checks whether the firm has the funds, people and capabilities to deliver the strategy.",
  },
  {
    id: 69,
    topic: "Strategic choice - Financial appraisal",
    prompt: "When appraising a strategic investment, a positive net present value (NPV) indicates the project:",
    options: ["Should be rejected", "Is expected to add value at the discount rate used", "Has no risk", "Ignores the time value of money"],
    answer: 1,
    explanation: "A positive NPV means the project is expected to increase shareholder value given the cost of capital.",
  },
  {
    id: 70,
    topic: "Strategic choice - Investment appraisal",
    prompt: "A drawback of the payback period method for strategic decisions is that it:",
    options: ["Considers all cash flows and the time value of money", "Ignores cash flows after the payback point", "Is impossible to calculate", "Always agrees with NPV"],
    answer: 1,
    explanation: "Payback ignores cash flows beyond the payback point and, in its simple form, the time value of money.",
  },
  {
    id: 71,
    topic: "Strategic choice - Risk and uncertainty",
    prompt: "Sensitivity analysis helps strategic decision-making by showing:",
    options: ["The exact future outcome", "How sensitive the result is to changes in key variables", "The competitor's profit", "The tax authority's view"],
    answer: 1,
    explanation: "Sensitivity analysis identifies how much a key variable can change before the decision changes.",
  },
  {
    id: 72,
    topic: "Strategic choice - Real options",
    prompt: "Treating a strategic investment as a 'real option' recognises the value of:",
    options: ["Committing fully and irreversibly now", "Flexibility to expand, delay or abandon later", "Ignoring uncertainty", "Removing all management choice"],
    answer: 1,
    explanation: "Real options value managerial flexibility to adapt - expand, defer or abandon - as uncertainty resolves.",
  },
  {
    id: 73,
    topic: "Strategic choice - Strategy and structure",
    prompt: "Chandler's famous proposition about strategy and structure is that:",
    options: ["Structure should drive strategy", "Structure follows strategy", "They are unrelated", "Strategy is irrelevant"],
    answer: 1,
    explanation: "Chandler argued 'structure follows strategy' - organisational design should support the chosen strategy.",
  },
  {
    id: 74,
    topic: "Strategic choice - Organisational structure",
    prompt: "A divisional (M-form) structure organises the business primarily by:",
    options: ["Specialist function only", "Products, markets or geographic divisions", "Random allocation", "A single central department"],
    answer: 1,
    explanation: "Divisional structures group activities into semi-autonomous divisions by product, market or region.",
  },
  {
    id: 75,
    topic: "Strategic choice - Matrix structure",
    prompt: "A frequently cited disadvantage of a matrix structure is:",
    options: ["Clear single lines of authority", "Dual reporting causing potential conflict and slower decisions", "No need for coordination", "Complete absence of specialists"],
    answer: 1,
    explanation: "Matrix structures create dual authority, which can cause conflict and slow decision-making.",
  },
  {
    id: 76,
    topic: "Strategic choice - Mintzberg's configurations",
    prompt: "In Mintzberg's configurations, a young, simple firm dominated by its owner is a:",
    options: ["Machine bureaucracy", "Simple structure", "Divisionalised form", "Adhocracy"],
    answer: 1,
    explanation: "The simple structure is small, flexible and centred on a single leader or owner.",
  },
  {
    id: 77,
    topic: "Strategic choice - Make or buy",
    prompt: "In a make-or-buy (outsourcing) decision, an organisation should usually keep in-house activities that are:",
    options: ["Core and a source of competitive advantage", "Routine and non-core", "Easily bought cheaply outside", "Of no strategic importance"],
    answer: 0,
    explanation: "Core, advantage-creating activities are usually retained, while non-core ones may be outsourced.",
  },
  {
    id: 78,
    topic: "Strategic choice - Stakeholder acceptability",
    prompt: "A strategy with high expected returns but unacceptable to powerful stakeholders is likely to:",
    options: ["Be implemented without issue", "Face resistance that threatens implementation", "Have no consequences", "Automatically succeed"],
    answer: 1,
    explanation: "Even profitable strategies can fail if key stakeholders find them unacceptable and resist.",
  },
  {
    id: 79,
    topic: "Strategic choice - Decision trees",
    prompt: "Decision trees assist strategic choice under uncertainty by:",
    options: ["Removing all probabilities", "Mapping options, outcomes and probabilities to compute expected values", "Guaranteeing the best result", "Ignoring future events"],
    answer: 1,
    explanation: "Decision trees structure sequential decisions and uncertain outcomes to calculate expected values.",
  },
  {
    id: 80,
    topic: "Strategic choice - Cost of capital",
    prompt: "Using too low a discount rate when appraising strategic projects can lead to:",
    options: ["Rejecting all projects", "Accepting projects that do not truly add value", "No effect on decisions", "Perfectly accurate appraisal"],
    answer: 1,
    explanation: "An understated discount rate overstates NPVs, risking acceptance of value-destroying projects.",
  },

  // ---------------------------------------------------------------------------
  // E3 syllabus area E: Strategic control
  // ---------------------------------------------------------------------------
  {
    id: 81,
    topic: "Strategic control - Balanced scorecard",
    prompt: "Kaplan and Norton's balanced scorecard includes financial, customer, internal business process and:",
    options: ["Tax perspective", "Learning and growth perspective", "Weather perspective", "Competitor perspective"],
    answer: 1,
    explanation: "The four perspectives are financial, customer, internal process, and learning and growth.",
  },
  {
    id: 82,
    topic: "Strategic control - Balanced scorecard",
    prompt: "A key benefit of the balanced scorecard is that it:",
    options: ["Uses only financial measures", "Links a range of financial and non-financial measures to strategy", "Ignores customers", "Measures nothing"],
    answer: 1,
    explanation: "The scorecard balances financial and non-financial measures aligned to strategic objectives.",
  },
  {
    id: 83,
    topic: "Strategic control - Critical success factors",
    prompt: "Critical success factors (CSFs) are best described as:",
    options: ["The few areas where the organisation must excel to succeed", "Every minor task", "Only accounting ratios", "The CEO's hobbies"],
    answer: 0,
    explanation: "CSFs are the limited number of areas in which satisfactory results ensure competitive success.",
  },
  {
    id: 84,
    topic: "Strategic control - KPIs",
    prompt: "The relationship between CSFs and KPIs is that KPIs:",
    options: ["Replace CSFs", "Measure performance against CSFs", "Are unrelated to CSFs", "Are always financial"],
    answer: 1,
    explanation: "KPIs are the measures used to track progress on the organisation's critical success factors.",
  },
  {
    id: 85,
    topic: "Strategic control - Strategic vs financial control",
    prompt: "Compared with financial control, a strategic control style places more emphasis on:",
    options: ["Short-term budget targets only", "Long-term strategic objectives and non-financial measures", "Daily cash counting", "Ignoring strategy"],
    answer: 1,
    explanation: "Strategic control emphasises long-term goals, accepting more non-financial and longer-term measures.",
  },
  {
    id: 86,
    topic: "Strategic control - Performance pyramid",
    prompt: "The performance pyramid (Lynch and Cross) links corporate vision to operations by:",
    options: ["Cascading objectives and measures down the organisation", "Using only one top-level number", "Removing all measures", "Focusing solely on share price"],
    answer: 0,
    explanation: "The pyramid translates vision into objectives and measures at each level, linking strategy to operations.",
  },
  {
    id: 87,
    topic: "Strategic control - Performance prism",
    prompt: "A distinctive feature of the performance prism is that it begins with:",
    options: ["Stakeholder satisfaction and contribution", "Only shareholder returns", "Inventory levels", "Office rent"],
    answer: 0,
    explanation: "The performance prism starts from stakeholder needs and contributions rather than purely financial measures.",
  },
  {
    id: 88,
    topic: "Strategic control - Non-financial measures",
    prompt: "Which of the following is a non-financial performance measure?",
    options: ["Return on capital employed", "Customer satisfaction rating", "Gross profit margin", "Earnings per share"],
    answer: 1,
    explanation: "Customer satisfaction is a non-financial measure; the others are financial.",
  },
  {
    id: 89,
    topic: "Strategic control - Strategic management accounting",
    prompt: "Strategic management accounting is characterised by its focus on:",
    options: ["Internal historical data only", "External, competitor-oriented and forward-looking information", "Only payroll", "Only tax compliance"],
    answer: 1,
    explanation: "Strategic management accounting looks outward and forward - at competitors, markets and strategy.",
  },
  {
    id: 90,
    topic: "Strategic control - Benchmarking",
    prompt: "Benchmarking supports strategic control by:",
    options: ["Setting targets based on best practice and identifying improvement gaps", "Ignoring competitors", "Removing all measurement", "Fixing prices"],
    answer: 0,
    explanation: "Benchmarking compares performance with best practice to set targets and find improvement opportunities.",
  },
  {
    id: 91,
    topic: "Strategic control - Reward systems",
    prompt: "A risk of linking executive reward too closely to short-term financial KPIs is:",
    options: ["Improved long-term investment", "Dysfunctional short-termism and gaming of measures", "Better stakeholder balance", "No behavioural effect"],
    answer: 1,
    explanation: "Over-reliance on short-term targets can drive short-termism and manipulation of measures.",
  },
  {
    id: 92,
    topic: "Strategic control - Business process re-engineering",
    prompt: "Business process re-engineering (BPR) involves:",
    options: ["Minor incremental tweaks", "Fundamental rethinking and radical redesign of processes", "Leaving processes unchanged", "Only renaming departments"],
    answer: 1,
    explanation: "BPR (Hammer and Champy) is the radical redesign of processes to achieve dramatic performance gains.",
  },
  {
    id: 93,
    topic: "Strategic control - Change management (Lewin)",
    prompt: "Lewin's three-step change model is unfreeze, change (move) and:",
    options: ["Refreeze", "Reverse", "Remove", "Reduce"],
    answer: 0,
    explanation: "Lewin's model is unfreeze, change, then refreeze to embed the new state.",
  },
  {
    id: 94,
    topic: "Strategic control - Change management (Kotter)",
    prompt: "The first step in Kotter's eight-step change model is to:",
    options: ["Declare victory early", "Create a sense of urgency", "Cut the budget", "Reduce communication"],
    answer: 1,
    explanation: "Kotter's model begins by establishing a sense of urgency for change.",
  },
  {
    id: 95,
    topic: "Strategic control - Resistance to change",
    prompt: "A common reason employees resist strategic change is:",
    options: ["Too much job security", "Fear of the unknown and perceived loss", "Excessive communication", "Clear personal benefit"],
    answer: 1,
    explanation: "Resistance often stems from fear of the unknown and perceived loss of status, security or competence.",
  },
  {
    id: 96,
    topic: "Strategic control - Types of change",
    prompt: "In Balogun and Hope Hailey's change matrix, incremental change that realigns (rather than transforms) the organisation is called:",
    options: ["Adaptation", "Revolution", "Reconstruction", "Evolution"],
    answer: 0,
    explanation: "Adaptation is incremental change within the existing paradigm (realignment rather than transformation).",
  },
  {
    id: 97,
    topic: "Strategic control - Change agents",
    prompt: "The role of a 'change agent' is to:",
    options: ["Block change", "Lead and facilitate the change process", "Audit the accounts", "Set dividend policy"],
    answer: 1,
    explanation: "A change agent champions, leads and facilitates the implementation of change.",
  },
  {
    id: 98,
    topic: "Strategic control - Feedforward control",
    prompt: "Feedforward control differs from feedback control because it:",
    options: ["Acts only after results are known", "Anticipates problems and acts before deviations occur", "Ignores the future", "Is purely historical"],
    answer: 1,
    explanation: "Feedforward control is proactive, anticipating deviations and acting before they happen.",
  },
  {
    id: 99,
    topic: "Strategic control - Budgets and strategy",
    prompt: "A limitation of traditional budgeting as a strategic control tool is that it can:",
    options: ["Encourage long-term strategic thinking", "Be short-term, rigid and encourage gaming", "Always reflect strategy perfectly", "Remove the need for KPIs"],
    answer: 1,
    explanation: "Traditional budgets are often short-term and rigid and can encourage dysfunctional behaviour.",
  },
  {
    id: 100,
    topic: "Strategic control - Implementation",
    prompt: "A major reason that otherwise good strategies fail is:",
    options: ["Excellent implementation", "Poor implementation and weak change management", "Too much stakeholder support", "Clear communication"],
    answer: 1,
    explanation: "Many sound strategies fail due to poor execution, weak control and inadequate change management.",
  },

  // ---------------------------------------------------------------------------
  // E3 syllabus area F: Digital strategy
  // ---------------------------------------------------------------------------
  {
    id: 101,
    topic: "Digital strategy - Fourth Industrial Revolution",
    prompt: "The 'Fourth Industrial Revolution' (Industry 4.0) is characterised by:",
    options: ["Steam power", "The fusion of digital, physical and biological technologies", "The first assembly lines", "Only paper records"],
    answer: 1,
    explanation: "Industry 4.0 blends digital, physical and biological systems such as IoT, AI and cyber-physical systems.",
  },
  {
    id: 102,
    topic: "Digital strategy - Cloud computing",
    prompt: "A key strategic benefit of cloud computing is:",
    options: ["High upfront capital cost", "Scalability and pay-as-you-go flexibility", "Loss of all data access", "No need for internet"],
    answer: 1,
    explanation: "Cloud offers scalable, on-demand resources usually on a pay-as-you-go basis, reducing upfront capital expenditure.",
  },
  {
    id: 103,
    topic: "Digital strategy - Internet of Things",
    prompt: "The Internet of Things (IoT) refers to:",
    options: ["Only social media apps", "Networks of connected physical devices that collect and share data", "Paper-based filing", "A type of tax"],
    answer: 1,
    explanation: "IoT connects physical objects with sensors and connectivity to collect and exchange data.",
  },
  {
    id: 104,
    topic: "Digital strategy - Data as an asset",
    prompt: "Treating 'data as an asset' implies that organisations should:",
    options: ["Delete all data immediately", "Manage, protect and exploit data to create value", "Never analyse data", "Ignore data governance"],
    answer: 1,
    explanation: "Treating data as a strategic asset means governing and exploiting it to create competitive value.",
  },
  {
    id: 105,
    topic: "Digital strategy - Analytics types",
    prompt: "Descriptive analytics primarily answers the question:",
    options: ["What is likely to happen next?", "What has happened?", "What should we do?", "Why will it happen?"],
    answer: 1,
    explanation: "Descriptive analytics summarises what has happened using historical data.",
  },
  {
    id: 106,
    topic: "Digital strategy - Analytics types",
    prompt: "Prescriptive analytics goes further than predictive analytics by:",
    options: ["Only describing the past", "Recommending actions to achieve a desired outcome", "Recording transactions", "Deleting data"],
    answer: 1,
    explanation: "Prescriptive analytics suggests the best course of action, often using optimisation or AI.",
  },
  {
    id: 107,
    topic: "Digital strategy - Artificial intelligence",
    prompt: "Machine learning is best described as systems that:",
    options: ["Follow fixed rules that never change", "Learn patterns from data and improve with experience", "Cannot process data", "Only print reports"],
    answer: 1,
    explanation: "Machine learning enables systems to learn from data and improve performance without explicit reprogramming.",
  },
  {
    id: 108,
    topic: "Digital strategy - Robotic process automation",
    prompt: "Robotic process automation (RPA) is most suited to:",
    options: ["Creative strategy formulation", "High-volume, repetitive, rule-based tasks", "Board-level judgement", "Negotiating contracts"],
    answer: 1,
    explanation: "RPA automates structured, repetitive, rule-based tasks, freeing staff for higher-value work.",
  },
  {
    id: 109,
    topic: "Digital strategy - Blockchain",
    prompt: "A defining feature of blockchain (distributed ledger) technology is:",
    options: ["A single central editable database", "A shared, tamper-evident ledger distributed across participants", "Paper certificates", "No security at all"],
    answer: 1,
    explanation: "Blockchain is a distributed, cryptographically secured ledger that is very difficult to alter retrospectively.",
  },
  {
    id: 110,
    topic: "Digital strategy - Digital disruption",
    prompt: "Digital disruption typically threatens incumbents because new entrants:",
    options: ["Always have higher costs", "Use technology to offer new value and bypass traditional models", "Avoid customers", "Never scale"],
    answer: 1,
    explanation: "Digital disruptors use technology and new business models to create value and challenge established firms.",
  },
  {
    id: 111,
    topic: "Digital strategy - Platform business models",
    prompt: "A platform (multi-sided) business model creates value mainly by:",
    options: ["Owning all assets and inventory", "Connecting and facilitating exchange between different user groups", "Avoiding all customers", "Selling only one product once"],
    answer: 1,
    explanation: "Platforms create value by enabling interactions and exchanges between two or more groups, such as buyers and sellers.",
  },
  {
    id: 112,
    topic: "Digital strategy - Network effects",
    prompt: "A 'network effect' means a product or platform becomes more valuable as:",
    options: ["Fewer people use it", "More people use it", "Prices rise", "Data is deleted"],
    answer: 1,
    explanation: "With network effects, each additional user increases the value of the product or platform for other users.",
  },
  {
    id: 113,
    topic: "Digital strategy - Disintermediation",
    prompt: "'Disintermediation' in a digital context refers to:",
    options: ["Adding more middlemen", "Removing intermediaries to deal directly with customers", "Increasing paperwork", "Closing the website"],
    answer: 1,
    explanation: "Disintermediation cuts out intermediaries, letting producers reach customers directly, often online.",
  },
  {
    id: 114,
    topic: "Digital strategy - Digital business models",
    prompt: "A 'freemium' digital business model works by:",
    options: ["Charging everyone the same high fee", "Offering a basic service free and charging for premium features", "Giving everything away forever", "Refusing free trials"],
    answer: 1,
    explanation: "Freemium provides a free basic tier and monetises premium features or upgrades.",
  },
  {
    id: 115,
    topic: "Digital strategy - Digital ecosystems",
    prompt: "A digital ecosystem typically relies on:",
    options: ["Closed, isolated systems", "Open interfaces such as APIs that let partners integrate", "No external partners", "Manual paper processes"],
    answer: 1,
    explanation: "Digital ecosystems use open interfaces and APIs so partners and complementors can connect and add value.",
  },
  {
    id: 116,
    topic: "Digital strategy - Digital transformation",
    prompt: "Digital transformation is best understood as:",
    options: ["Buying one new laptop", "Fundamentally changing operations, models and culture using digital technology", "Only updating the logo", "Ignoring technology"],
    answer: 1,
    explanation: "Digital transformation reshapes processes, business models and culture through technology - not just isolated IT purchases.",
  },
  {
    id: 117,
    topic: "Digital strategy - Strategy alignment",
    prompt: "A digital strategy should be:",
    options: ["Separate from and unrelated to business strategy", "Aligned with and integrated into the overall business strategy", "Only about buying hardware", "Decided without management"],
    answer: 1,
    explanation: "An effective digital strategy is integrated with, and supports, the organisation's overall strategy.",
  },
  {
    id: 118,
    topic: "Digital strategy - Cybersecurity",
    prompt: "From a strategic risk perspective, a major cyber-attack can damage an organisation's:",
    options: ["Reputation, finances and operations", "Nothing of importance", "Only the IT helpdesk", "Only paper files"],
    answer: 0,
    explanation: "Cyber incidents can cause financial loss, operational disruption and serious reputational damage.",
  },
  {
    id: 119,
    topic: "Digital strategy - Information security",
    prompt: "The CIA triad in information security stands for confidentiality, integrity and:",
    options: ["Availability", "Authority", "Audit", "Accuracy"],
    answer: 0,
    explanation: "The CIA triad is Confidentiality, Integrity and Availability of information.",
  },
  {
    id: 120,
    topic: "Digital strategy - Customer experience",
    prompt: "An 'omnichannel' customer strategy aims to:",
    options: ["Use only one sales channel", "Provide a seamless, integrated experience across all channels", "Avoid online channels", "Confuse customers"],
    answer: 1,
    explanation: "Omnichannel delivers a consistent, integrated customer experience across physical and digital channels.",
  },
  {
    id: 121,
    topic: "Digital strategy - Data governance",
    prompt: "Effective data governance is important because it:",
    options: ["Reduces data quality", "Ensures data is accurate, secure, compliant and usable", "Encourages data breaches", "Removes accountability"],
    answer: 1,
    explanation: "Data governance provides the policies and accountability needed to keep data accurate, secure and compliant.",
  },
  {
    id: 122,
    topic: "Digital strategy - Role of finance",
    prompt: "In digital transformation, the modern finance function is increasingly expected to:",
    options: ["Only process invoices", "Provide data-driven insight and partner with the business", "Avoid technology", "Ignore strategy"],
    answer: 1,
    explanation: "Finance is shifting from transaction processing toward data-driven business partnering and insight.",
  },
  {
    id: 123,
    topic: "Digital strategy - Agile ways of working",
    prompt: "'Agile' approaches support digital strategy by enabling:",
    options: ["Long, fixed multi-year plans only", "Iterative delivery and rapid adaptation to change", "No customer feedback", "Avoidance of all change"],
    answer: 1,
    explanation: "Agile uses short iterations and feedback to adapt quickly, which suits fast-changing digital contexts.",
  },
  {
    id: 124,
    topic: "Digital strategy - Data monetisation",
    prompt: "'Data monetisation' means:",
    options: ["Destroying data for tax reasons", "Generating economic value from data assets", "Hiding data from managers", "Stopping data collection"],
    answer: 1,
    explanation: "Data monetisation creates economic value from data, directly through sale or insight, or indirectly through better decisions.",
  },
  {
    id: 125,
    topic: "Digital strategy - Additive manufacturing",
    prompt: "Additive manufacturing (3D printing) can strategically affect supply chains by:",
    options: ["Forcing larger central factories", "Enabling localised, on-demand and customised production", "Eliminating all design", "Preventing prototyping"],
    answer: 1,
    explanation: "3D printing supports decentralised, on-demand and customisable production, reshaping supply chains.",
  },
  {
    id: 126,
    topic: "Digital strategy - Big data sources",
    prompt: "Which of the following is an example of unstructured data?",
    options: ["A numeric sales ledger", "Social-media text and images", "A balance sheet", "A fixed-format database table"],
    answer: 1,
    explanation: "Unstructured data such as text, images and video lacks a predefined data model, unlike structured tables.",
  },
  {
    id: 127,
    topic: "Digital strategy - Sustainable advantage",
    prompt: "Technology is most likely to create sustainable advantage when it is:",
    options: ["Freely and instantly copyable by all rivals", "Combined with distinctive capabilities and hard to imitate", "Never linked to strategy", "Used in isolation from customers"],
    answer: 1,
    explanation: "Technology becomes a durable advantage when embedded in capabilities and complementary assets rivals cannot easily copy.",
  },
  {
    id: 128,
    topic: "Digital strategy - Responding to disruption",
    prompt: "An incumbent facing digital disruption should generally:",
    options: ["Ignore it and hope it passes", "Monitor, experiment and be willing to cannibalise existing models", "Ban all new technology", "Stop serving customers"],
    answer: 1,
    explanation: "Incumbents respond best by sensing change, experimenting and sometimes disrupting themselves before others do.",
  },
  {
    id: 129,
    topic: "Digital strategy - Analytics risks",
    prompt: "A risk of relying on data analytics for strategic decisions is:",
    options: ["Perfectly unbiased results always", "Poor data quality or bias leading to flawed conclusions", "No need for judgement", "Guaranteed success"],
    answer: 1,
    explanation: "'Garbage in, garbage out' - biased or poor-quality data can mislead decisions, so human judgement remains essential.",
  },
  {
    id: 130,
    topic: "Digital strategy - Customer power",
    prompt: "Digital technologies have increased customer power partly because:",
    options: ["Customers have less information", "Price, quality and review information is widely and instantly available", "Switching is now impossible", "Brands are hidden"],
    answer: 1,
    explanation: "Easy access to information, reviews and comparisons online increases customer bargaining power.",
  },
  {
    id: 131,
    topic: "Digital strategy - Data ethics",
    prompt: "An ethical concern in using big data and analytics is:",
    options: ["Improved transparency only", "Privacy, consent and potential algorithmic bias", "No concerns at all", "Lower data volumes"],
    answer: 1,
    explanation: "Using personal data raises issues of privacy, consent and bias that must be managed ethically and lawfully.",
  },
  {
    id: 132,
    topic: "Digital strategy - Digital value chain",
    prompt: "Digital technology can enhance the value chain mainly by:",
    options: ["Slowing information flow", "Improving information flow, automation and integration across activities", "Removing all customers", "Eliminating analysis"],
    answer: 1,
    explanation: "Digital tools improve information flow, automate activities and integrate the value chain, enhancing efficiency and value.",
  },
];

export const getQuestions = (): CimaE3Question[] => questions;

export const getNextQuestionIndex = (currentIndex: number, totalQuestions: number): number =>
  (currentIndex + 1) % totalQuestions;

export const getRandomQuestionIndex = (
  currentIndex: number,
  totalQuestions: number,
): number => {
  if (totalQuestions <= 1) {
    return 0;
  }

  let nextIndex = Math.floor(Math.random() * totalQuestions);
  while (nextIndex === currentIndex && totalQuestions > 1) {
    nextIndex = Math.floor(Math.random() * totalQuestions);
  }

  return nextIndex;
};

export const formatBreakTime = (seconds: number): string => {
  const minutes = Math.floor(seconds / 60);
  const remainingSeconds = seconds % 60;
  return `${String(minutes).padStart(2, "0")}:${String(remainingSeconds).padStart(2, "0")}`;
};
